"""Tests for the plain-text email renderer."""

from src.email_text import render_text


class TestRenderText:
    """Tests for the render_text function."""

    def test_adds_header_with_date_range(self, sample_report_markdown: str) -> None:
        """Should prepend a header containing the date range."""
        result = render_text(sample_report_markdown, "Test Range", 0.85, True)
        assert result.startswith("AI Industry Weekly - Test Range\n")
        assert "=" * 60 in result

    def test_strips_leading_h1(self, sample_report_markdown: str) -> None:
        """Should strip the leading # AI Industry Weekly H1 from the body."""
        result = render_text(sample_report_markdown, "Test Range", 0.85, True)
        # The H1 should not appear anywhere (header does not include # prefix)
        assert "# AI Industry Weekly" not in result

    def test_preserves_body_content(self, sample_report_markdown: str) -> None:
        """Should keep the markdown body intact."""
        result = render_text(sample_report_markdown, "Test Range", 0.85, True)
        assert "## Industry Overview" in result
        assert "### Big AI Labs" in result
        assert "Google" in result
        assert "OpenAI" in result
        assert "Community Updates" in result

    def test_appends_footer_with_pass(self, sample_report_markdown: str) -> None:
        """Should append a footer with PASS label."""
        result = render_text(sample_report_markdown, "Test Range", 0.85, True)
        assert result.endswith("Generated by AIReport · eval 0.85/1.0 (PASS)")
        assert "-" * 60 in result

    def test_appends_footer_with_fail(self, sample_report_markdown: str) -> None:
        """Should append a footer with FAIL label."""
        result = render_text(sample_report_markdown, "Test Range", 0.35, False)
        assert result.endswith("Generated by AIReport · eval 0.35/1.0 (FAIL)")
        assert "(PASS)" not in result

    def test_score_formatted_to_two_decimals(self, sample_report_markdown: str) -> None:
        """Should format the eval score to 2 decimal places."""
        result = render_text(sample_report_markdown, "Test Range", 0.666666, True)
        assert "eval 0.67/1.0" in result

    def test_empty_markdown(self) -> None:
        """Should handle empty markdown gracefully."""
        result = render_text("", "Empty Date", 0.0, False)
        assert result.startswith("AI Industry Weekly - Empty Date\n")
        assert "eval 0.00/1.0 (FAIL)" in result

    def test_no_leading_h1(self) -> None:
        """Should handle markdown without a leading H1."""
        body = "## Section 1\n\nSome content here.\n\n## Section 2\n\nMore content."
        result = render_text(body, "No H1", 0.9, True)
        assert "## Section 1" in result
        assert "## Section 2" in result
        assert result.startswith("AI Industry Weekly - No H1\n")
        assert "eval 0.90/1.0 (PASS)" in result
