"""Tests for the Hacker News-themed email template."""

import html

import pytest

from src.email_template import render_html


class TestEmailTemplate:
    """Validate the HN email renderer output structure and styling."""

    @pytest.fixture
    def sample_report(self) -> str:
        """A small markdown report covering all major elements."""
        return """# AI Industry Weekly - July 18 - July 25, 2026

## Industry Overview

### Big AI Labs
- **Google**: Announced Gemini 3.0 with improved reasoning [1]
- **OpenAI**: Released GPT-5 with enhanced coding abilities [2][3]

### Smaller Labs
- Mistral released a new open-weights model
- DeepSeek announced breakthroughs in efficiency

## Sources

1. [Google Gemini announcement](https://example.com/google)
2. [OpenAI GPT-5](https://example.com/openai)
3. [Extra commentary](https://example.com/extra)
"""

    def test_returns_complete_html_document(self, sample_report: str) -> None:
        """The renderer must return a full HTML document."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.85, True)
        assert result.startswith("<!DOCTYPE html>")
        assert "<html" in result
        assert "</html>" in result
        assert "<body>" in result
        assert "</body>" in result

    def test_header_band_and_footer(self, sample_report: str) -> None:
        """Header and footer contain the expected metadata and escaping."""
        date_range = "July 18 - July 25, 2026"
        result = render_html(sample_report, date_range, 0.85, True)
        assert "AI Industry Weekly" in result
        assert date_range in result
        assert "Generated by AIReport" in result
        assert "eval 0.85/1.0 (PASS)" in result
        assert 'bgcolor="#ff6600"' in result

    def test_escapes_injected_metadata(self, sample_report: str) -> None:
        """User-supplied metadata should be HTML-escaped in the output."""
        malicious_date = "<script>alert('x')</script>"
        result = render_html(sample_report, malicious_date, 0.85, True)
        assert "<script>" not in result
        assert html.escape(malicious_date) in result

    def test_section_headings_styled(self, sample_report: str) -> None:
        """Section headings receive the HN section class."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.85, True)
        assert 'class="hn-section"' in result
        assert "Industry Overview" in result
        assert "Sources" in result

    def test_subsection_headings_styled(self, sample_report: str) -> None:
        """Sub-section headings receive the HN subsection class."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.85, True)
        assert 'class="hn-subsection"' in result
        assert "Big AI Labs" in result

    def test_bullet_lists_use_upvote_triangle(self, sample_report: str) -> None:
        """Bullet lists use the HN upvote triangle marker."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.85, True)
        assert "▴" in result
        assert 'class="hn-upvote"' in result
        assert 'class="hn-list"' in result

    def test_bold_lead_ins_are_orange(self, sample_report: str) -> None:
        """Bold lead-ins in list items are highlighted with the HN orange."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.85, True)
        assert 'class="hn-lead"' in result
        assert "Google" in result
        assert "OpenAI" in result

    def test_citations_are_orange_badges(self, sample_report: str) -> None:
        """Inline citation markers are styled as small orange badges."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.85, True)
        assert 'class="hn-cite"' in result
        assert "[1]" in result
        assert "[2]" in result
        assert "[3]" in result

    def test_source_list_appends_urls(self, sample_report: str) -> None:
        """The sources section appends gray monospace URLs after each link."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.85, True)
        assert 'class="hn-sources"' in result
        assert 'class="hn-source-url"' in result
        assert "https://example.com/google" in result
        assert "https://example.com/openai" in result

    def test_links_are_orange(self, sample_report: str) -> None:
        """All anchors receive the HN orange link styling."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.85, True)
        assert 'class="hn-link"' in result
        assert "color:#ff6600" in result

    def test_eval_fail_label(self, sample_report: str) -> None:
        """A failing evaluation renders FAIL in the footer."""
        result = render_html(sample_report, "July 18 - July 25, 2026", 0.55, False)
        assert "(FAIL)" in result
        assert "(PASS)" not in result
