"""Plain-text alternative body for the AI weekly report email.

Renders a readable text version of the report for email clients that prefer
text or have HTML disabled. Markdown is already human-readable, so we keep it
largely intact and add a header/footer with the report metadata.
"""

from __future__ import annotations

import re


def render_text(
    report_markdown: str,
    date_range: str,
    eval_score: float,
    eval_passed: bool,
) -> str:
    """Render the report as a plain-text email alternative.

    Args:
        report_markdown: The raw markdown content from the manager agent.
        date_range: The date range string for the report.
        eval_score: Final evaluation score (0.0-1.0).
        eval_passed: Whether the report passed evaluation.

    Returns:
        Plain-text string suitable for the text/plain part of a multipart email.
    """
    eval_label = "PASS" if eval_passed else "FAIL"
    header = f"AI Industry Weekly - {date_range}\n{'=' * 60}\n\n"
    footer = (
        f"\n\n{'-' * 60}\n"
        f"Generated by AIReport · eval {eval_score:.2f}/1.0 ({eval_label})"
    )

    body = report_markdown.strip()
    # Drop the leading H1 title — the header above already carries it.
    body = re.sub(r"^#\s+AI Industry Weekly[^\n]*\n+", "", body, count=1)
    return header + body + footer